name: Node.js CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies
      run: npm i
      
    - name: Creating environment file
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "CLIENT_HOST=${{ secrets.CLIENT_HOST }}" >> .env
        echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test